[package]
name = "op"
version = "0.1.0"
authors = ["amiya <amiya19mandal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15"
csv = "1.1"